In [1]:
import numpy as np

In [57]:
X_train = np.array([[1000.0, 2.0], [1500.0, 3.0]])

In [40]:
X_train

array([[1000. ,    2. ],
       [1500. ,    3. ],
       [1250. ,    2.5],
       [1780. ,    5. ]])

In [4]:
# Grab all rows from first column
X_train[:, 0]

array([1000., 1500.])

In [6]:
# Grab all columns from first row
X_train[0, :]

array([1000.,    2.])

In [7]:
np.min(X_train[:,0])

1000.0

In [8]:
np.mean(X_train[:,0])

1250.0

In [43]:
def max_min_s(a):
    output = []
    for col_i in range(0, len(a[0])):
        min = np.min(a[:,col_i])
        max = np.max(a[:,col_i])
        range_val = max - min
        
        for row_i in range(0, len(a[:,0])):
            if col_i == 0:
                output.append([])
            output[row_i].append((a[row_i, col_i]-min)/range_val)
            
    return output

In [44]:
print(max_min_s(X_train))

[[0.0, 0.0], [0.6410256410256411, 0.3333333333333333], [0.32051282051282054, 0.16666666666666666], [1.0, 1.0]]


In [45]:
from sklearn import preprocessing

In [47]:
min_max_scaler = preprocessing.MinMaxScaler()

In [48]:
X_minmax = min_max_scaler.fit_transform(X_train)

In [49]:
X_minmax

array([[0.        , 0.        ],
       [0.64102564, 0.33333333],
       [0.32051282, 0.16666667],
       [1.        , 1.        ]])

In [58]:
def standard_scaler(a):
    output = []
    for col_i in range(0, len(a[0])):
        mean = np.mean(a[:, col_i])
        std = np.std(a[:, col_i])
        for row_i in range(0, len(a[:,0])):
            if col_i == 0:
                output.append([])
            output[row_i].append((a[row_i, col_i]-mean)/std)
            
    return output

In [59]:
print(standard_scaler(X_train))

[[-1.0, -1.0], [1.0, 1.0]]


In [60]:
def standard_scaler(a):
    return ((a - a.mean(axis=0)) / a.std(axis=0))

In [61]:
print(standard_scaler(X_train))

[[-1. -1.]
 [ 1.  1.]]


In [62]:
standard_scaler = preprocessing.StandardScaler()
X_ss = standard_scaler.fit_transform(X_train)
print(X_ss)

[[-1. -1.]
 [ 1.  1.]]


In [63]:
import pandas as pd

In [92]:
df = pd.read_csv('churn_modelling.csv')

In [97]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [66]:
df['Geography'].value_counts()

France     5014
Germany    2509
Spain      2477
Name: Geography, dtype: int64

In [67]:
df['Gender'].value_counts()

Male      5457
Female    4543
Name: Gender, dtype: int64

In [98]:
X = df.iloc[:, 3:13].values

In [99]:
y = df.iloc[:, 13].values

In [78]:
print(X[0:10, :])

[[619 'France' 'Female' 42 2 0.0 1 1 1 101348.88]
 [608 'Spain' 'Female' 41 1 83807.86 1 0 1 112542.58]
 [502 'France' 'Female' 42 8 159660.8 3 1 0 113931.57]
 [699 'France' 'Female' 39 1 0.0 2 0 0 93826.63]
 [850 'Spain' 'Female' 43 2 125510.82 1 1 1 79084.1]
 [645 'Spain' 'Male' 44 8 113755.78 2 1 0 149756.71]
 [822 'France' 'Male' 50 7 0.0 2 1 1 10062.8]
 [376 'Germany' 'Female' 29 4 115046.74 4 1 0 119346.88]
 [501 'France' 'Male' 44 4 142051.07 2 0 1 74940.5]
 [684 'France' 'Male' 27 2 134603.88 1 1 1 71725.73]]


In [80]:
from sklearn.preprocessing import LabelEncoder

In [81]:
label_encoder_X_1 = LabelEncoder()
X[:,1] = label_encoder_X_1.fit_transform(X[:,1])

In [82]:
label_encoder_X_2 = LabelEncoder()
X[:,2] = label_encoder_X_2.fit_transform(X[:,2])

In [83]:
print(X[0:10, :])

[[619 0 0 42 2 0.0 1 1 1 101348.88]
 [608 2 0 41 1 83807.86 1 0 1 112542.58]
 [502 0 0 42 8 159660.8 3 1 0 113931.57]
 [699 0 0 39 1 0.0 2 0 0 93826.63]
 [850 2 0 43 2 125510.82 1 1 1 79084.1]
 [645 2 1 44 8 113755.78 2 1 0 149756.71]
 [822 0 1 50 7 0.0 2 1 1 10062.8]
 [376 1 0 29 4 115046.74 4 1 0 119346.88]
 [501 0 1 44 4 142051.07 2 0 1 74940.5]
 [684 0 1 27 2 134603.88 1 1 1 71725.73]]


In [100]:
X = df.iloc[:, 3:13]

In [101]:
pd.get_dummies(X).head(10)

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619   42       2       0.00              1          1   
1          608   41       1   83807.86              1          0   
2          502   42       8  159660.80              3          1   
3          699   39       1       0.00              2          0   
4          850   43       2  125510.82              1          1   
5          645   44       8  113755.78              2          1   
6          822   50       7       0.00              2          1   
7          376   29       4  115046.74              4          1   
8          501   44       4  142051.07              2          0   
9          684   27       2  134603.88              1          1   

   IsActiveMember  EstimatedSalary  Geography_France  Geography_Germany  \
0               1        101348.88                 1                  0   
1               1        112542.58                 0                  0   
2               0        113931.57                 1                  0   
3               0         93826.63                 1                  0   
4               1         79084.10                 0                  0   
5               0        149756.71                 0                  0   
6               1         10062.80                 1                  0   
7               0        119346.88                 0                  1   
8               1         74940.50                 1                  0   
9               1         71725.73                 1                  0   

   Geography_Spain  Gender_Female  Gender_Male  
0                0              1            0  
1                1              1            0  
2                0              1            0  
3                0              1            0  
4                1              1            0  
5                1              0            1  
6                0              0            1  
7                0              1            0  
8                0              0            1  
9                0              0            1

In [68]:
def convert_geography(x):
    print(x)
    if x == 'France':
        x = 1
    if x == 'Germany':
        x = 2
    if x == 'Spain':
        x = 3

In [72]:
hi = df['Geography'].apply(convert_geography)

0       None
1       None
2       None
3       None
4       None
        ... 
9995    None
9996    None
9997    None
9998    None
9999    None
Name: Geography, Length: 10000, dtype: object